# Generated by Django 5.1 on 2024-08-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_password_machanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_reset_token', models.CharField(blank=True, max_length=100)),
                ('password_reset_token_created', models.DateTimeField(null=True)),
            ],
        ),
    ]
